# ROLLING
strategy:
  rolling:
    maxParallel: 50%

###

# BLUE-GREEN DEPLOYMENT
# two environments "Blue" and "Green" are used for production
# "Blue" serves traffic, while "Green" is updated with the new release
# Once the relase is verified traffic is switched from "Blue" environment to "Green" making the new version live

strategy:
  runOnce:
    preDeploy:
      steps:
      - script: echo "Setting up new environment"
    deploy:
      steps:
      - script: echo "Deploying new version"
    routeTraffic:
      steps:
      - script: echo "Routing traffic to new version"

###
# CANARY
# new version of the app is rolled out to a small subset of users first
# this small portion of users ("canary group") acts as a test group
# if tests perform well, the deployment is gradually expanded to the rest of the user base

strategy:
  canary:
    increments: 2
    deploy:
      steps:
      - script: echo "Deploying canary release"
